language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - composer require --dev scrutinizer/ocular --no-interaction
  - composer require --dev php-coveralls/php-coveralls --no-interaction

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage.clover
  - php vendor/bin/php-coveralls
